name: persian_datetime_picker
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 2.5.1

homepage: https://github.com/M-amir-M/persian-datetime-picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: 0.18.0
  flutter_svg: ^2.0.4
#  pub_sub: ^1.0.0

dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/icons/

